### ISSUE TITLE
doesn`t work with Mendeley

### ISSUE THREAD

**Issue by akvaton** [myshevchuk/dstu-csl#2]
This CSL file is not supported by Mendeley. The error is:
<The downloaded file doesn't seem to be a CSL file>
Probably it`s a minor syntactic error to be corrected.

**Comment by myshevchuk** [comment]
@akvaton The CSL file is OK. Use the "raw" URL to download the file via Mendeley interface: 

https://raw.githubusercontent.com/myshevchuk/dstu-csl/master/dstu-8302-2015.csl

**Comment by akvaton** [comment]
@myshevchuk perfect! thank you very much!
